### ISSUE TITLE
Italian language option

### ISSUE THREAD

**Issue by danilaric** [bedapudi6788/deepsegment#10]
Hi, 
as stated in the medium blog (https://medium.com/@praneethbedapudi/deepsegment-2-0-multilingual-text-segmentation-with-vector-alignment-fd76ce62194f) seems that in previuous commits there was an option for the Italian language.

Do you plan to re-add the Italian language as an option for the package?

Thanks

**Comment by bedapudi6788** [comment]
For now, you will have to use the version from master branch. I will add french, italian and other languages in a few weeks.

**Comment by bedapudi6788** [comment]
@danilaric "french" (fr) and "itaian" (it) are now available.
