### ISSUE TITLE
How to train a new model using custom data 

### ISSUE THREAD

**Issue by leolcling** [bedapudi6788/deepsegment#13]
I have prepared the data using `data_gen.py` in master branch, how do I train a new model?

**Comment by bedapudi6788** [comment]
@leolcling I added functions to train deepsegment. Please take a look at https://colab.research.google.com/drive/1CjYbdbDHX1UmIyvn7nDW2ClQPnnNeA_m to see an example on how to do this.

**Comment by hanifabd** [comment]
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

i got that error on the  last step, can you help me, please
