### ISSUE TITLE
segment_long, n_window optimal length

### ISSUE THREAD

**Issue by tcollins590** [bedapudi6788/deepsegment#14]
**Describe the bug and error messages (if any)**
This is not a bug, however a request for clarification on the optimal length of n_window based on the string length. Is there a factor that should be considered when setting n_window? I am feeding in various length phrases to be broken up, so I could see setting this dynamically.

Thank you

**Comment by bedapudi6788** [comment]
@tylercollins590 the value is very much dependent on the type of data. ideally, i would set n_window=2*number of words in expected sentences. Please note that, it is more of a hacky approach for segmenting long sentences. It would work better if you fine-tune the model on your data.

**Comment by tcollins590** [comment]
I will do some testing with the suggestion you made below and let you know
how the results pan out. I likely will run a fine tuned model in a few
weeks. Thank you feel free to close this.
