### ISSUE TITLE
Deepcorrect not working on model trained using Deepsegment.

### ISSUE THREAD

**Issue by sangeet2020** [bedapudi6788/deepsegment#18]
Hello,

Apologies if the headline isn't to the point.
Actually I used Deepsegment (https://colab.research.google.com/drive/1CjYbdbDHX1UmIyvn7nDW2ClQPnnNeA_m#scrollTo=K9oMoDwwXgQl) to train a language model on my custom data. However when I use the trained model (HDF format) and parms (JSON format) and run the code below:

**### My logic: czech-data -> DeepSegment -> train mode -> DeepCorrect -> punctuated and segmented sentences**

```
from deepcorrect import DeepCorrect                                                                                                                                                                         
DeepCorrect('/home/sagar/.DeepSegment_cs/params', '/home/sagar/.DeepSegment_cs/checkpoint')

```
There is an error that 
```
UnpicklingError: invalid load key, '{'
```
As far I understand correctly, deep correct expects the params file to be a pickle file and not a plain text JSON file.
Is there anything wrong with my approach?

Thank You

**Comment by bedapudi6788** [comment]
I think you misunderstood something somewhere. DeepSegment and DeepCorrect are two different libraries with two different model architectures. You have to train both separately and use both separately.

**Comment by sangeet2020** [comment]
Could  you please share the instruction to train model for deepcorrect ?

**Comment by bedapudi6788** [comment]
https://github.com/bedapudi6788/txt2txt/

**Comment by bedapudi6788** [comment]
@sangeet2020 I am closing the issue, feel free to re-open if you have any other questions.

**Comment by sangeet2020** [comment]
Sure Mr. Praneeth. Thanks a lot.
I had a question, I am trainning Deepsegment using tensorflow2.0, will this be an issue or any effect on the model ?

**Comment by bedapudi6788** [comment]
> will this be an issue or any effect on the model ?

No. Latest versions of both deepsegment and txt2txt support newer tf and keras versions.
