### ISSUE TITLE
Deep Segment model available for download is read only 

### ISSUE THREAD

**Issue by bsatish417** [bedapudi6788/deepsegment#2]
Hi,

Deep segment model available for download is read only, while trying to load the model it's throwing error:

PermissionError: [Errno 13] Permission denied: 'models/deepsegment_eng'

I tried to remove read only options in security tab of folder, and couple of other options but nothing works. could you please look in to it ?

Thanks

**Comment by bedapudi6788** [comment]
Hi @bsatish417 can you add the snippet of code you used for loading the model here. And the contents of the config file.

**Comment by bsatish417** [comment]
Hi @bedapudi6788 , Here is the code

from deepsegment import DeepSegment
segmenter = DeepSegment('models/deepsegment_eng')

Few screenshots to show the model location & read only box that is not going away no matter what do.
![1](https://user-images.githubusercontent.com/6218752/53650446-2a634880-3c0a-11e9-927d-a4fb23f1b303.png)
![2](https://user-images.githubusercontent.com/6218752/53650479-3fd87280-3c0a-11e9-9c3f-02a6aebe8c9c.png)

**Comment by bedapudi6788** [comment]
@bsatish417 , you need to pass the path of the config file to DeepSegment(). You will fins config.json file inside the downloaded model. Change the dir_output to the path in your local machine and pass the path of that config.json to DeepSegment()

**Comment by bsatish417** [comment]
i did that already, please find attached config values and error 
![1](https://user-images.githubusercontent.com/6218752/53686215-fbbc9f00-3ce9-11e9-892c-c74c70652c31.png)
![2](https://user-images.githubusercontent.com/6218752/53686216-fbbc9f00-3ce9-11e9-9859-fb4966d83562.png)

**Comment by bsatish417** [comment]
Never mind, i figured it out. Model doesn't seems to segment all. It was not able to segment the below text 

51541 250 PERFORMED 4-WHEEL ALIGNMENT AS PER CUSTOMER, RECOMMENDED REPLACING FRONT TIRES BUT THEY DECLINED REPLACING THEM, PASS

Any thoughts ? The idea is to capture what is performed, what is recommended & what is declined.

![1](https://user-images.githubusercontent.com/6218752/53687501-d5532f80-3cfa-11e9-8ccc-382c781d02ec.png)

**Comment by bedapudi6788** [comment]
@bsatish417 It doesn't look like what you are trying to do is a straight forward sentence segmentation task. To get good results you will need to train a NER model on your data to extract the entities you want.

**Comment by bsatish417** [comment]
Thanks a lot.

**Comment by Inadel** [comment]
hi, can you give me the full config for deepsegment in french sentence segmentation?
thanks you
