### ISSUE TITLE
Hi I trained a model in spanish woud you like to add to?

### ISSUE THREAD

**Issue by sersoage** [bedapudi6788/deepsegment#20]

**Comment by sersoage** [comment]
Also I am unable to load that trained model even if I set a lang_code='None', is there a way to load a model in another lang? Thanks!

**Comment by bedapudi6788** [comment]
@sersoage Can you send me the params, utils and checkpoint. I will test and add to the repo.

**Comment by bedapudi6788** [comment]
@sersoage I just checked and, lang_code=None should have worked. Can you post the error/ logs you are getting.
