### ISSUE TITLE
Training other language

### ISSUE THREAD

**Issue by Tortoise17** [bedapudi6788/deepsegment#23]
I have a question. Is it possible to train such for other languages as well? If you can guide how to do this?

**Comment by bedapudi6788** [comment]
Yes. Please take a look at the training section in readme. 

https://colab.research.google.com/drive/1CjYbdbDHX1UmIyvn7nDW2ClQPnnNeA_m
The above notebook shows the complete process.

**Comment by bedapudi6788** [comment]
Please re-open if you get any errors.
