### ISSUE TITLE
Train with a different language

### ISSUE THREAD

**Issue by JuanFF** [bedapudi6788/deepsegment#35]
Hello,
I have followed the guide to train a custom DeepSegment that you published on colab.research.google.com
I want to try it on Spanish, so I used a custom corpus of sentences in Spanish and a custom vector file from this corpus.
After training, the checkpoint is saved and then I use DeepSegment as follows:
segmenter = DeepSegment(checkpoint_name='checkpoint')
I didn't specify "es" as Spanish is not supported, so I think that "english" is loaded by default in the object.
Is this the right way to train a different language?
Thanks!

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/deepsegment/blob/51df6e4d11091c3e0ac2b3ce71b9e19a4cc87371/deepsegment/deepsegment.py#L99
```python
DeepSegment(lang_code=None, checkpoint_path='CHECKPOINT_PATH', params_path='PARAMS_PATH', utils_path='UTILS_PATH')
```

this is the correct format.

**Comment by JuanFF** [comment]
Thanks a lot! By the way, what is the appropriate number of sentences I should provide for a fine model?

**Comment by bedapudi6788** [comment]
In `x, y = generate_data(lines, max_sents_per_example=6, n_examples=10000)` I would suggest at least 100k lines and n_examples=lines*3. If you lines is high enough (eg: 1 mil), n_examples = lines is also fine

**Comment by JuanFF** [comment]
Hi!
Sorry for re-opening the question. I want to make sure that I am giving the right configuration for training.

I have a dataset of 630K sentence lines from different sources.

I had to exclude lines with less than 3 tokens, otherwise, I get `ValueError: empty range for randrange()` and I assume that I can't provide too short sentences for training, am I right?

As for generate_data(), I've set the following:

`x, y = generate_data(lines[315000:], max_sents_per_example=6, n_examples=len(lines[315000:]))`
`vx, vy = generate_data(lines[:315000], max_sents_per_example=6, n_examples=len(lines[:315000]))`

Does it make sense to include all lines instead? I mean:
`x, y = generate_data(lines, max_sents_per_example=6, n_examples=len(lines))`

By the way, should data in x,y and vx,vy be different? In other words, what should be the difference between both sets?

Thank you very much!

**Comment by bedapudi6788** [comment]
> Sorry for re-opening the question.

No problem!

> I had to exclude lines with less than 3 tokens, otherwise, I get ValueError: empty range for randrange() and I assume that I can't provide too short sentences for training, am I right?

Yupp!

> Does it make sense to include all lines instead? I mean:

Yes. I would suggest keep n_examples = 2 * len(lines[315000:]). But, even your values will be fine.

> By the way, should data in x,y and vx,vy be different? In other words, what should be the difference between both sets?

vx, vy is used for validation. i.e: To make sure the model is not overfitting to train set.


Your values, splitting looks fine. You should get a good model.

**Comment by bedapudi6788** [comment]
Also, since you have 630K lines, use 600k for x,y and 30k for vx, vy. 315 is too much for vx, vy.

**Comment by bedapudi6788** [comment]
@JuanFF feel free to re-open the issue if you need any other info.

**Comment by JuanFF** [comment]
Thanks a lot! The training is on its way... I made a quick test and I'm positively impressed. 
The input texts are very long strings (around 2000 tokens per text unit). So, I must use `.segment_long() ` I am not clear on the n_window parameter, is there a value I should set here?

**Comment by bedapudi6788** [comment]
You will have to manually experiment with n_window from 10-30 and see which gives better results. Also, compare these results with the normal segment function once. Pretty good chance both perform similarly.

**Comment by JuanFF** [comment]
The results seem fine.
I see, however, that some split sentences keep too long. Let me explain this.
My original text source (more than 2000 tokens) is split into sentences with an average of 20-35 tokens, which is fine. Unfortunately, some of these output sentences have around 200 tokens. I suppose that they are false negatives, as `segement_long` couldn't find any boundaries in there.
So my last question - is it possible to set a maximum number of tokens for the resulting split sentences?

**Comment by bedapudi6788** [comment]
Try re-segmenting the longer sentences (you can have a simple logic like if len(sent.split()) > 100: resegment) with segment function again. This is a little hacky but might work.

> So my last question - is it possible to set a maximum number of tokens for the resulting split sentences?

Currently, there is no way to do this out of the box.

**Comment by JuanFF** [comment]
Thanks a lot for your help. Your solution makes sense but it doesn't work : ( 
For some text slices, `segment` can't find the boundaries, even if I apply it again as you said. If I am right, the only possible solution for this then lies in the training phase.
I must say that my input text is an ASR transcription with missing words and too noisy passages. I suppose that it is normal that DeepSegment can't work in such cases.
