### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by hanifabd** [bedapudi6788/deepsegment#37]
i make my own dataset and i make glove in my own using word2vec, and i got this issue on the last step

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

can tell me why

**Comment by bedapudi6788** [comment]
@hanifabd what are your tensorflow and keras versions?

**Comment by hanifabd** [comment]
oh ya i got the problem, i use colab an the tensorflow version is newest one, thanks
