### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by maxaalexeeva** [bedapudi6788/deepsegment#39]
**Describe the bug and error messages (if any)**
Can't import the module

**The code snippet which gave this error***
```

Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepsegment import DeepSegment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'deepsegment'
```

**Specify versions of the following libraries**
1. deepsegment - possibly 1.0.1 (this is the message I get when installing using `pip install -upgrade deepsegment`: _Successfully installed deepsegment-1.0.1 logging-0.4.9.6 numpy-1.16.6 seqtag-1.0.3_
2. tensorflow/ tensorflow-gpu - 1.14.0
3. keras - 2.3.1

**Expected behavior**
I expected for the module to be imported and to be able to follow the examples in the README

Thank you!

**Comment by bedapudi6788** [comment]
Can you post the output for the following commands

```bash
python -V
pip -V
pip show deepsegment
python -m pip -V
```

**Comment by maxaalexeeva** [comment]
Thank you for a quick response!
```
(base) alexeeva@pop-os:~$ python -V
Python 3.7.3
(base) alexeeva@pop-os:~$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
(base) alexeeva@pop-os:~$ pip show deepsegment
Name: deepsegment
Version: 1.0.1
Summary: Sentence Segmentation with sequece tagging
Home-page: https://github.com/bedapudi6788/Deep-Segmentation
Author: BEDAPUDI PRANEETH
Author-email: praneethbedapudi@gmail.com
License: GPLv3
Location: /home/alexeeva/.local/lib/python2.7/site-packages
Requires: seqtag
(base) alexeeva@pop-os:~$ python -m pip -V
/home/alexeeva/miniconda3/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
```

**Comment by bedapudi6788** [comment]
the default pip and python versions are different (i.e: the command pip is linked to python2.7). can you also post the output for the following commands (run them in the same order).

```bash
ls
python -m ensurepip
python -m pip --version
python -m pip install --upgrade deepsegment
```

**Comment by maxaalexeeva** [comment]
the output of ls is basically all my stuff - a lot of things. Anything in particular I should be seeing?

And I get this error while running python -m pip --version:

```
(base) alexeeva@pop-os:~$ python -m ensurepip
Looking in links: /tmp/tmpugd85vtw
Requirement already satisfied: setuptools in ./miniconda3/lib/python3.7/site-packages (46.1.3.post20200330)
Requirement already satisfied: pip in ./miniconda3/lib/python3.7/site-packages (19.3.1)
(base) alexeeva@pop-os:~$ python -m pip --version
/home/alexeeva/miniconda3/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
``

**Comment by bedapudi6788** [comment]
> the output of ls is basically all my stuff - a lot of things. Anything in particular I should be seeing?

check if there is any file or directory named `pip` in the directory from which you are running these commands.

Or better, create a new empty directory and cd inside it and repeat the `python -m pip --version` again. It should ideally output the pip version you are using. Only then, you will be able to install any modules for the python version you are using.

**Comment by maxaalexeeva** [comment]
@bedapudi6788 same error in the empty directory. But it sounds like this is an issue unrelated to the module itself, so I will try to figure that out. Thank you for the advice!

**Comment by bedapudi6788** [comment]
@maxaalexeeva closing the issue for now.

**Comment by maxaalexeeva** [comment]
@bedapudi6788, got it working in a new conda environment with these keras and tensorflow versions you indicate as tested (keras==2.3.1; tensorflow==2.2.0) and ran segment_long on a couple of unpunctuated speech transcripts about 130 words long each. Very happy with the result. Thank you!
