### ISSUE TITLE
module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by sourabh-zanwar** [bedapudi6788/deepsegment#40]
Versions: 

> 1. deepsegment 2.3.1
> 2. tensorflow 2.4.0
> 3. keras 2.3.1

Problem:
As I try to run the basic code for Sentence Segmentation 
```
from deepsegment import DeepSegment
d = 'this is a sentence this is another sentence'
segmenter = DeepSegment('en')
d_seg = segmenter.segment(d)
```

I get the following error:
`AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`

**Comment by bedapudi6788** [comment]
# Tested with (keras==2.3.1; tensorflow==2.2.0) and (keras==2.2.4; tensorflow==1.14.0)

**Comment by Emekaborisama** [comment]
Did you resolve this issue because i am getting the same error

**Comment by bedapudi6788** [comment]
@Emekaborisama with the specified tensorflow versions?
