### ISSUE TITLE
tensorflow serving

### ISSUE THREAD

**Issue by uriva** [bedapudi6788/deepsegment#5]
Hey!
I want to use this with tensorflow serving but having trouble understanding how to generate an hd5 file. Any ideas how I can do that?

Thanks

**Comment by bedapudi6788** [comment]
@uriva , the general process is: load the checkpoints into graph. Take a look at the graph in tensorboard and figure out the input and output nodes, export to .pb. 

I am currently thinking of training a new version (with some more data). will take a look at tf serving part along with that.

**Comment by guyling** [comment]
Tensorflow  serving does not support RNN (LSTM being an instance of which) natively since it does not support internal state memory.  There are some work around nir they hamper performance

**Comment by bedapudi6788** [comment]
> Tensorflow serving does not support RNN (LSTM being an instance of which) natively since it does not support internal state memory. 
 
This is not true. You are mixing up stateful RNNs (LSTMs) and stateless RNNs (LSTMs). Sequence Tagging (the general BiLSTM CRF implementation), doesn't need stateful lstms

**Comment by bedapudi6788** [comment]
@uriva @guyling  tf-serving is available now. Take a look at the readme.
