### ISSUE TITLE
`download` function described in blog post isn't there?

### ISSUE THREAD

**Issue by uriva** [bedapudi6788/deepsegment#6]
From the blog post:

```
pip install --upgrade deepsegment
import deepsegment
deepsegment.download('eng_fra_ita')
```

This doesn't seem to work (there is no `download` method).

**Comment by bedapudi6788** [comment]
@uriva I wasn't able to find a stable, free place to upload the pre-trained checkpoints so that, they can be downloaded. Right now, they are present in the deepsegment-models repo, but git lfs has a bandwidth uppercap.

So, for now, you will have to manually download the files from there. :(

**Comment by bedapudi6788** [comment]
@uriva I just released DeepSegment v2. This can download the models automatically and configures their path automatically.

**Comment by uriva** [comment]
I'm getting some sklearn related error when trying to install, which is weird because I have sklearn (0.21.3).

**Comment by bedapudi6788** [comment]
Can you please post the error that you got? I will check it out.

**Comment by uriva** [comment]
> Command "/home/uriva/my_project/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pa43k108/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-11oeb3hr/install-record.txt --single-version-externally-managed --compile --install-headers /home/uriva/my_project/venv/include/site/python3.7/scikit-learn" failed with error code 1 in /tmp/pip-install-pa43k108/scikit-learn/

**Comment by bedapudi6788** [comment]
Can you once please check if you are able to install in a new enviroment (venv or conda). I am unable to reproduce this. Might be because of some library you already have installed.

**Comment by uriva** [comment]
btw I'm using python 3.7.3 in case it matters.
