### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5665: character maps to <undefined>

### ISSUE THREAD

**Issue by Jack-Collins** [bedapudi6788/deepsegment#7]
I get this error when I try to initialize a segmenter like so using pre-trained model suggested https://github.com/bedapudi6788/DeepSegment-Models:

```
segmenter = deepsegment.DeepSegment(
    config_path='content_creation/ai_pretrained_models/deepsegment_eng_v1/deepsegment_eng_v1/config.json'
)
```

Error: 
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5665: character maps to <undefined>

```

Is there an issue with the pre-trained model, or have I set up something wrong ?

**Comment by bedapudi6788** [comment]
Can you try running in a new environment with locale and lang set to UTF-8

**Comment by bedapudi6788** [comment]
I just released v2 of this model. Please check and re-open the issue if the issue still exists.
