### ISSUE TITLE
Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

### ISSUE THREAD

**Issue by michaelyao** [bedapudi6788/deepsegment#8]
I am trying to run the sample code on google colab, and I got error:

Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

Here is the shared colab. 

https://colab.research.google.com/drive/16dVsf_4J_HCAuBn_aNZXQ6qFd44h2gEC

Here is code I tried. The error happened at : segmenter = DeepSegment('en')

from deepsegment import DeepSegment
segmenter = DeepSegment('en')
segmenter.segment('I am Batman i live in gotham')
['I am Batman', 'i live in gotham']

**Comment by bedapudi6788** [comment]
@michaelyao please make the colab link public. I am unable to access it.

**Comment by bedapudi6788** [comment]
@michaelyao the error was from a newer version of keras. I updated the setup.py to reflect it. It will work from now.
Note: if it still doesn't work as expected, run ```pip install keras==2.2.4``` and it will work as expected.

**Comment by urmay** [comment]
@bedapudi6788  
hi i am working on lstm -CRF for NER .I got the same error as mentioned by @michaelyao  
first i was getting this error :
`TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.
`
After installing  `pip install keras==2.2.4 ` 

it gives me : `super(type, obj): obj must be an instance or subtype of type`

**Comment by bedapudi6788** [comment]
@urmay how is this repo related to your comment?

**Comment by WEN-MIN** [comment]
I have meet the some question. Is there any good solution to solve this problem except  pip install keras==2.2.4？

**Comment by bedapudi6788** [comment]
@WEN-MIN I will update the seqtag-keras library to address this. Meanwhile, this is the only solution.

**Comment by bedapudi6788** [comment]
@WEN-MIN @michaelyao i updated the libraries to work with latest versions of tf and keras.
