### ISSUE TITLE
Unable to load "eng_fra_ita" with DeepSegment 

### ISSUE THREAD

**Issue by sl-victormazzeo** [bedapudi6788/deepsegment#9]
Hello, I am trying to load the eng_fra_ita model with the current branch v2, but it is not made available. Is there a way to load it? 

P.S. I also dowloaded the zip file from deepsegment-model but there is no "utils" and "params" files.

Thank you

**Comment by bedapudi6788** [comment]
v2 currently only supports english language. I will release models for other languages as soon as i can.

**Comment by sl-victormazzeo** [comment]
Ok thank you

**Comment by sbenigeri** [comment]
hey, thank you for making this. Do you know when v2 will support the eng_fra_ita model ?
Thanks

**Comment by bedapudi6788** [comment]
@sbenigeri @militu v2 now supports french and italian
